paths:
  /api/products/:
    post:
      summary: Agregar un producto a la DB.
      description: La ruta permite agregar un producto a la base de datos. Se requiere autenticaciòn y autorizaciòn.
      tags:
        - Product
      security:
        - BearerToken: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/schemas/Product'
      responses:
        '201':
          description: Producto creado con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data: 
                    $ref: '#components/schemas/productExample'
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
              $ref: '#components/schemas/Errors'
        '401':
          description: Error de autorización
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: error
                    example: error
                  message:
                    type: string
                    example: Authorization has not been sent!
        '500':
          description: Error interno en el servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    $ref: '#components/schemas/ServerErrors'
    get:
      summary: Devuelve una paginación de productos.
      description: La ruta devuelve una paginación de productos desde la DB. Se le pueden pasar filtros.
      tags:
        - Product
      parameters:
        - name: limit
          in: query
          description: Cantidad de productos por pagina.
          schema:
            type: number
            example: 5
        - name: page
          in: query
          description: El numero de pagina que se desea consultar.
          schema:
            type: number
            example: 3
        - name: sort
          in: query
          description: Orden de los datos recibidos. -1 ordena de mayor a menor, 1 de menor a mayor.
          schema:
            type: number
            example: 1
        - name: filter
          in: query
          description: Campo del producto por el que se desea realizar la busqueda.
          schema:
            type: string
            description: "El filtro se pasa en un objeto como key->value. {title: Cortante batman}"
            example: '"price": 345'
      responses:
        '200':
          description: Producto creado con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data: 
                    $ref: '#components/schemas/productPagination'
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
              $ref: '#components/schemas/Errors'
        '500':
          description: Error interno en el servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    $ref: '#components/schemas/ServerErrors'
  /api/products/{pid}:
    get:
      summary: Consultar un producto.
      description: La ruta devuelve un producto pasando por parametro su id. 
      tags:
        - Product
      parameters:
        - name: pid
          in: path
          description: Codigo de identificación de tipo Mongo id.
          schema:
            type: string
            example: 644afdde5138593c6da796fa
      responses:
        '200':
          description: Producto creado con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data: 
                    $ref: '#components/schemas/Product'
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
              $ref: '#components/schemas/Errors'
        '500':
          description: Error interno en el servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    $ref: '#components/schemas/ServerErrors'
    put:
      summary: Actualizar producto.
      description: Actualiza un producto en la DB. La ruta requiere autenticación y autorización.
      tags:
        - Product
      security:
        - BearerToken: []
      parameters:
        - name: pid
          in: path
          description: Codigo de identificación de tipo Mongo id.
          schema:
            type: string
            example: 644afdde5138593c6da796fa
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              description: Objeto que representa los campos y sus valores que se desean actualizar en el producto.
              example:
                status: false
      responses:
        '200':
          description: Producto creado con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data: 
                    $ref: '#components/schemas/Product'
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
              $ref: '#components/schemas/Errors'
        '500':
          description: Error interno en el servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    $ref: '#components/schemas/ServerErrors'
    delete:
      summary: Borrar un producto.
      description: Borra un producto en la DB. La ruta requiere autenticación y autorización.
      tags:
        - Product
      security:
        - BearerToken: []
      parameters:
        - name: pid
          in: path
          description: Codigo de identificación de tipo Mongo id.
          schema:
            type: string
            example: 644afdde5138593c6da796fa
      responses:
        '200':
          description: Producto borrado con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data: 
                    $ref: '#components/schemas/Product'
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
              $ref: '#components/schemas/Errors'
        '500':
          description: Error interno en el servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  error:
                    $ref: '#components/schemas/ServerErrors'
            